stages:
  - build
  - deploy

build-dev:
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest -f ./Dockerfile .
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE
  only:
    - development
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

deploy-dev:
  stage: deploy
  before_script:
    - mv docker-compose.dev.yml docker-compose.yml
  script:
    - docker-compose up -d
    - docker image prune -f
  only:
    - development

build-prod:
  image: docker:19.03.5
  services:
    - docker:19.03.5-dind
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:latest -f ./Dockerfile .
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE
  only:
    - main
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

deploy-prod:
  stage: deploy
  before_script:
    - mv docker-compose.prod.yml docker-compose.yml
  script:
    - docker-compose up -d
    - docker image prune -f
  only:
    - main