version: "3.9"
services:
  iteung-android-api-golang-dev:
    environment:
      - TZ=Asia/Jakarta
      - APP_ENV=dev
      - DB_USERNAME_SIAP=irc
      - DB_PASSWORD_SIAP=crot
      - DB_HOST_SIAP=localhost
      - DB_PORT_SIAP=3306
      - DB_NAME_SIAP=siap
    image: $CI_REGISTRY_IMAGE:latest
    container_name: iteung-android-api-golang-dev
    restart: unless-stopped
    expose:
      - "8080"
    networks:
      iteungwebnet:
        ipv4_address: 172.18.0.56

networks:
  iteungwebnet:
    external:
      name: iteungwebnet
